"""Add structured job fields

Revision ID: 580234aa2e11
Revises: c653f1f649ff
Create Date: 2026-08-12 17:53:59.629574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '580234aa2e11'
down_revision: Union[str, Sequence[str], None] = 'c653f1f649ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('min_experience', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_experience', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('education_requirements', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('jobs', sa.Column('salary_disclosure', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('match_threshold', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('number_of_openings', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.drop_column('jobs', 'number_of_openings')
    op.drop_column('jobs', 'match_threshold')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_disclosure')
    op.drop_column('jobs', 'education_requirements')
    op.drop_column('jobs', 'max_experience')
    op.drop_column('jobs', 'min_experience')
    # ### end Alembic commands ###
